name: ikmb-metagenome-1.2
channels:
  - biobakery
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r=4.0
  - r-tidyverse
  - r-data.table
  - python=3.10
  - metabat2
  - metaphlan
  - humann
  - concoct=1.1.0
  - bowtie2
  - fastqc
  - gawk
  - pandas
  - samtools
  - sed
  - krakentools=1.2
  - minimap2
